### ISSUE TITLE
404 page not working?

### ISSUE THREAD

**Issue by iliketocode** [iliketocode/bored#20]
I have tried to make the 404 error page but it doesn't seem to work! Why? (NOTE: If you reply, please tag @funsites so it goes to my new account! :smile: )

**Comment by Mrcomputer1** [comment]
The 404 page must be in a repo called iliketocode.github.io or it won't work

**Comment by DrKat123** [comment]
Yeah, my bad for adding the .htaccess

**Comment by funsites** [comment]
OK!

**Comment by iliketocode** [comment]
Fixed it!

**Comment by iliketocode** [comment]
I made the update 20 minutes ago and it still isn't coming through to the site yet. (cleared cache 3 times)

**Comment by Mrcomputer1** [comment]
It still does not work. Try the master branch instead of gh-pages branch because Github User Pages uses master not gh-pages.

**Comment by DrKat123** [comment]
Yeah. I'll probably delete the pull request for the .htaccess now

**Comment by DrKat123** [comment]
It's closed :stuck-out-tongue:

**Comment by DrKat123** [comment]
I added the label wontfix and working on this, cuz u kno, it wont fix and i'm working on it :stuck_out_tongue_closed_eyes:

**Comment by iliketocode** [comment]
Deleted this iliketocode.github.io repository until we can try again.

**Comment by iliketocode** [comment]
Issue closed until further notice. If you wish to discuss the 404 error again, make a new issue or re -open this one.
